// <auto-generated />
namespace InTravels.DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class update_post_and_comment : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(update_post_and_comment));
        
        string IMigrationMetadata.Id
        {
            get { return "201610312035443_update_post_and_comment"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
